apiVersion: v1
kind: Service
metadata:
  name: bureaucrat
spec:
  ports:
  - port: 9998 
  selector:
    app: bureaucrat
  type: NodePort
  ports:  
  - name: sign
    port: 9998
    targetPort: 9998
    nodePort: 30998
    protocol: TCP   
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bureaucrat
spec:
  selector:
    matchLabels:
      app: bureaucrat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bureaucrat
    spec:
      containers:
      - image: bureaucrat
        name: bureaucrat
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9998
          name: sign
        volumeMounts:
          # name must match the volume name below
          - name: signing-keys
            mountPath: /mnt
      volumes:
        - name: signing-keys
          secret:
            secretName: signing-keys
