apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: leases
spec:
  schedule: "0 2 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: leases
            image: jobs
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: creds
                    key: aws-key 
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: creds
                    key: aws-secret
            command: ["/bin/sh","-c"]
            args: ["python3 leases.py"]
          restartPolicy: Never
      backoffLimit: 4
