kind: Service
apiVersion: v1
metadata:
  name: puppet
spec:
  selector:
    app: puppet
  ports:
  - name: http
    protocol: TCP
    port: 8140
    targetPort: 8140
  externalIPs:
  - 192.168.0.7
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: puppet
  name: puppet
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/puppet
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: puppet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: puppet
    spec:
      containers:
      - image: cloud.canister.io:5000/rralcala/puppet
        imagePullPolicy: IfNotPresent
        name: puppet
        ports:
        - containerPort: 8140
          name: puppet
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/puppet
          name: puppet-var
        - mountPath: /usr/share/pupeptcontent
          name: puppet-content
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/rralcala/pyeduca-infra/mothership/puppet/lib
          type: ""
        name: puppet-var
      - hostPath:
          path: /home/rralcala/pyeduca-infra/mothership/puppet/puppetcontent
          type: ""
        name: puppet-content
