apiVersion: v1
kind: Secret
metadata:
  name: pyeduca-tls
type: Opaque
---
apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
spec:
  backoffLimit: 1
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      - image: sjenning/kube-nginx-letsencrypt:0.8.1-1
        name: letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: a.paraguayeduca.org,inventario.paraguayeduca.org
        - name: EMAIL
          value: info@paraguayeduca.org
        - name: SECRET
          value: pyeduca-tls
        - name: DEPLOYMENT
          value: nginx
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
spec:
  selector:
    app: letsencrypt
  ports:
  - protocol: "TCP"
    port: 80