apiVersion: v1
kind: Secret
metadata:
  name: pyeduca-tls
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: default-role
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - secrets
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: default-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-role
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
spec:
  backoffLimit: 1
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      - image: sjenning/kube-nginx-letsencrypt:0.8.1-1
        name: letsencrypt
        imagePullPolicy: IfNotPresent
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: a.paraguayeduca.org,inventario.paraguayeduca.org
        - name: EMAIL
          value: info@paraguayeduca.org
        - name: SECRET
          value: pyeduca-tls
        - name: DEPLOYMENT
          value: nginx
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
spec:
  selector:
    app: letsencrypt
  ports:
  - protocol: "TCP"
    port: 80