apiVersion: v1
kind: Service
metadata:
  name: yaas-web
spec:
  ports:
  - port: 3000
  selector:
    app: yaas-web
  type: NodePort
  ports:  
  - name: yaas
    port: 3000
    targetPort: 3000
    nodePort: 30081
    protocol: TCP   
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: yaas-web
spec:
  selector:
    matchLabels:
      app: yaas-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yaas-web
    spec:
      containers:
      - image: docker.io/rralcala/yaas-web
        name: yaas-web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: yaas
        volumeMounts:
          # name must match the volume name below
          - name: yaas-config
            mountPath: /app/config/secrets/
      volumes:
        - name: yaas-config 
          secret:
            secretName: yaas-config 
