apiVersion: v1
kind: Service
metadata:
  name: yaas-web
spec:
  ports:
  - port: 80 
  selector:
    app: yaas-web
  type: NodePort
  ports:  
  - name: yaas
    port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP   
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: yaas-web
spec:
  selector:
    matchLabels:
      app: yaas-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yaas-web
    spec:
      containers:
      - image: yaas-web
        name: yaas-web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: yaas
        volumeMounts:
          # name must match the volume name below
          - name: yaas-config
            mountPath: /var/yaas-web/config/secrets/
      volumes:
        - name: yaas-config 
          secret:
            secretName: yaas-config 
