apiVersion: v1
kind: Service
metadata:
  name: inventario
spec:
  ports:
  - port: 80 
  selector:
    app: inventario
  ports:  
  - name: inventario
    port: 80
    protocol: TCP   
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: inventario
spec:
  selector:
    matchLabels:
      app: inventario
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
      - image: docker.io/rralcala/inventario
        name: inventario
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: inventario
        volumeMounts:
          # name must match the volume name below
          - name: inventario-config
            mountPath: /var/inventario/config/secrets/
      hostAliases:
      - hostnames:
        - inventario.paraguayeduca.org
        ip: 127.0.0.1
      volumes:
        - name: inventario-config 
          secret:
            secretName: inventario-config 
